### ISSUE TITLE
Talk: Performance monitoring with Zone.js

### ISSUE THREAD

**Issue by jahtalab** [AngularCamp/angularcamp.org#109]
This talk concerns performance monitoring in production. I will talk about why performance monitoring in production is mission-critical and about the challenges associated with it. I will share some practical methods to gather performance metrics using Zone.js and how it can help to gain in-depth insight into an application.

**Comment by xlozinguez** [comment]
@jahtalab did you give this talk? do you happen to have a video link or slide to share? or maybe an article? :) Thank you!
