### ISSUE TITLE
Arquitectura de web components con ng2 y npm para 100 aplicaciones web

### ISSUE THREAD

**Issue by cbastos** [AngularCamp/angularcamp.org#114]
**I'm submitting a ...**  (check one with "x")

[X] Talk
[ ] Workshop
[ ] Interest 
[ ] Support request => Please do not submit support requests here, use one of these channels: [twitter](https://twitter.com/AngularCamp) or [email](mailto:hello@angularcamp.org)

**Your Twitter handle*:**

cbastospc

**Your Name*:**

Carlos Bastos Pérez-Cuadrado

**Title:**

Arquitectura de web components con ng2 y npm para 100 aplicaciones web

**Abstract:**

Mostraremos el planteamiento de infrastructura, arquitectura lógica y arquitectura física inicial para el desarrollo de 100 aplicaciones web por un equipo de 100 desarrolladores con reutilización de componentes, ui controls, cómo utilizar un core común de utilidades para autorización, autenticación, errores, trazas, etc. Todo esto con angular2, webpack, testing con karma, sass, etc.

**Duration:** 

45 min

**Technical requirements:**

[X] No
[ ] Yes => Please share what do you need.

**Complexity:**

[X] Advanced
[ ] Intermediate
[ ] Beginner

**Language:**

[ ] English
[x] Spanish

**Have you delivered this contribution before?:**

[X] Yes => Please include links if available
[ ] No

**Other information:**

Se propone una evolución destilada de este material:
 - Charla sobre angular2 y npm online: https://www.youtube.com/watch?v=hxAT9kc46UA
 - Angular2 y npm: https://prezi.com/biodplswbafa/arquitectura-escalable-con-ng2-y-npm/
 - UI Controls & services layers: https://prezi.com/ppnnzm9smaz3/ui-controls-services-layers/

**Comment by davidpich** [comment]
@cbastos Can you update your contribution following the issue template? Thanks in advance!
