### ISSUE TITLE
Hybrid Apps in a Snap: Ionic Framework

### ISSUE THREAD

**Issue by ubchick** [AngularCamp/angularcamp.org#124]
**I'm submitting a ...**  (check one with "x")
[ ] Talk
[x] Workshop
[] Interest 
[ ] Support request => Please do not submit support requests here, use one of these channels: [twitter](https://twitter.com/AngularCamp) or [email](mailto:hello@angularcamp.org)

**Your Twitter handle*:**

lizbrownsays

**Your Name*:**
Liz Brown

**Title:**

Hybrid Apps in a Snap: Ionic Framework

**Abstract:**

Do you have an idea for a mobile app and you’re only familiar with HTML, CSS and JS? Does going native and writing the same code twice over sound daunting? Ionic is an amazing framework that allows one code base to produce 2 platforms! Hybrid apps are a great way to get your idea out there to all users. Learn about Ionic and build a basic mobile app in 1 hour.

This workshop includes:
– Brief intro/explanation of Ionic as a framework
– Installing Ionic
– Making A Basic App
– Bonus: Connecting it to a SaaS database

**Duration:** 

**Technical requirements:**

[ ] No
[x] Yes => Some experience with HTML/CSS/JS. Setup machine before workshop
Node.js
Run node -v in terminal
Go to nodejs.org/en/download to get the latest version

NPM Install
Run npm -v in terminal
Update to latest by running npm install npm@latest -g in terminal

**Complexity:**

[ ] Advanced
[ ] Intermediate
[x] Beginner

**Language:**

[x] English

**Have you delivered this contribution before?:**
[x] Yes => https://webjunto.com/hybrid-apps-snap/  https://womenintechsummit.net/philly_session/mobile-apps/
[ ] No

**Other information:**

**Comment by johannes-weber** [comment]
Hey @ubchick, could you add the duration of your Ionic talk please? That would help us a lot for doing the schedule on the 2nd day.
