### ISSUE TITLE
Office Hours

### ISSUE THREAD

**Issue by SanderElias** [AngularCamp/angularcamp.org#125]
**Your Twitter handle:** esosanderelias
**Your Name:** Sander Elias

**Abstract:**
In this session, we will have a couple of Angular GDE's available that will help you with your Angular(js) (or related) problem.  You can come sit and code with us.

**Duration:** 
This session will be open for at least 3 hours, a bit depending on demand. (and experts availability!)

**Technical requirements:**
A room with tables and power, Attendees bring their own system along so we can work on their issues.

**Complexity:**
[X ] Advanced
[X ] Intermediate
[X ] Beginner
There will be help available for all levels of attendees.

**Language:**
[x] English

**Comment by ByteDefault** [comment]
Great initiative @SanderElias !!

Count with me!

**Comment by Elecash** [comment]
Great initiative @SanderElias !!

Count with me!

**Comment by manekinekko** [comment]
I'm here to help if you need me 😉

**Comment by filipbech** [comment]
Im happy to help as well
