### ISSUE TITLE
Getting to know the ins and outs of testing in Angular [Talk]

### ISSUE THREAD

**Issue by kirjai** [AngularCamp/angularcamp.org#140]
**I'm submitting a ...**  (check one with "x")
[x] Talk

**Your Twitter handle*:**

kirjai

**Your Name*:**
Kirils Ladovs

**Title:**

Getting to know the ins and outs of testing in Angular

**Abstract:**

We will be covering how easy and simple it is to set up unit testing for any Angular entity, be it a component, a service, a guard, etc. We will also explore the powerful `DebugElement` that allows us to test the HTML very easily.

**Duration:** 

30min

**Technical requirements:**

[x] No
[ ] Yes => Please share what do you need.

**Complexity:**

[ ] Advanced
[x] Intermediate
[ ] Beginner

**Language:**

[x] English

**Have you delivered this contribution before?:**
[ ] Yes => Please include links if available
[x] No

**Other information:**

**Comment by davidpich** [comment]
Hi @kirjai ! Great contribution, can you please split it please into two contributions workshop and talk so people can vote what they prefer, thanks in advance!
