### ISSUE TITLE
ngFights: your Angular app for katas 

### ISSUE THREAD

**Issue by semagarcia** [AngularCamp/angularcamp.org#142]
**I'm submitting a ...**  
[ ] Talk
[ X ] Workshop
[ ] Interest 
**[ X ] Challenge (yes, we are creating a new one type!!)**
[ ] Support request

**Your Twitter handle*:**
* @semagarcia 
* @ardiadrianadri

**Your Name*:**
* José Manuel García (Sema)
* Adrián Ferreres

**Title:**
ngFights: your Angular app for playing katas against others ng-devs

**Abstract:**
During the AngularCamp you could enjoy with the coolest kata player developed with our loved JavaScript framework. The main idea is that the participants should challenge one each other until only one of them remains. This great victorious will be the winner of the first MiskoCup. The cup recognise the best Angular developer in the AngularCamp event.

**Duration:** 
3 hours depending on the number of attenders.

**Technical requirements:**
Your laptop, your brave and your best coding skills.

[ X ] No
[ ] Yes => Please share what do you need.

**Complexity:**

[ X ] Advanced
[ X ] Intermediate
[ X ] Beginner

**Language:**
[x] English

**Have you delivered this contribution before?:**
[ ] Yes => Please include links if available
[ X ] No

**Comment by kaplan81** [comment]
Wonderful initiative! I just hope Adrian und Sema don't compete, otherwise it would be as if Ramirez and Connor MacLeod were standing against the rest of the immortals. We would get creamed with their knowledge.

**Comment by ardiadrianadri** [comment]
Thank you for your words @kaplan81 but the Angular Camp is full of people which are better developers of us. We only want to have fun and learn with others doing which we like: CODING JS!!! 😸

**Comment by semagarcia** [comment]
I can't say it with better words...
