### ISSUE TITLE
Talk : 5 Apps One Code

### ISSUE THREAD

**Issue by saniyusuf** [AngularCamp/angularcamp.org#143]
**I'm submitting a ...**  (check one with "x")
[x] Talk
[ ] Workshop
[ ] Interest 
[ ] Support request => Please do not submit support requests here, use one of these channels: [twitter](https://twitter.com/AngularCamp) or [email](mailto:hello@angularcamp.org)

**Your Twitter handle*:**

saniyusuf

**Your Name*:**
Sani Yusuf

**Title:**

5 Apps One Code

**Abstract:**

30 Min

**Technical requirements:**

[x] No
[ ] Yes => Please share what do you need.

**Complexity:**

[ ] Advanced
[x] Intermediate
[ ] Beginner

**Language:**

[x] English

**Have you delivered this contribution before?:**
[ ] Yes => Please include links if available
[x] No

**Other information:**

**Comment by davidpich** [comment]
Hope you can join us next time Sani!
