### ISSUE TITLE
app is not bootstrapping correctly

### ISSUE THREAD

**Issue by hhg2288** [AngularCamp/angularcamp.org#2]
I just fork the repo and saw that when `npm start` i have to ho to `localhost:8080/#/home` to actually see de website.

if you dont mind, I can fix some things & do some changes so the app would be more modular: something like this maybe: https://github.com/hhg2288/webpack-angular1x-es6

let me know if its ok to you!

also, are you using less because yo like it or for a specific reason? maybe we can migrate it to Postcss??

I create a PR to fix some big issues with the app: https://github.com/AngularCamp/angularcamp.org/pull/3

this is the list of things I would change if you dont mind of course:

* migrate from less to PostCSS (plus some plugins (autoprefixer...)
* modularize the app, so the menu is a directive, footer & so on
* make every page (state) a component, so everything related to that state is in the same folder/place
* add an `extract-text-plugin` so we can have specific styles to different components in its place, but create a same output for all css, so we dont pollute the header with a lot of `style` tags
* create a Production-ready Build (with minification, sourcemaps...)

you can see some of the changes I suggest in the repo I linked above.
thanks!!

**Comment by nirkaufman** [comment]
@hhg2288 thanks for your contribution! . we know that there is a lot of stuff needed to be done, and you are more than welcome to PR.

**Comment by davidpich** [comment]
Hi @hhg2288 feel free to do any PR, thanks for contribute !

**Comment by hhg2288** [comment]
:+1:
