### ISSUE TITLE
Creating an Angular 2 component library

### ISSUE THREAD

**Issue by Elecash** [AngularCamp/angularcamp.org#36]
Angular 2 is the next evolution to the AngularJS framework and now the Beta release is out! 

With the new year it's a perfect time to start a side project and learn new things. Angular 2 comes with its own challenges like TypeScript compilation and functional programming. 

Come to learn how to deal with these new framework. We will focus in the creation of an Angular 2 reusable component, scoped styles and templates, publication and distribution to NPM.

**Comment by lcrespom** [comment]
+1
Is there a way to use GitHub to vote for proposals?

**Comment by Elecash** [comment]
@lcrespom no, there is not, and it sucks.

That's a long-time demanded feature by the community. Big frameworks are all full of "+1" comments that  are not contributing to the conversation threads in the issues.

There is a community complaint and signature call to try to fix several old problems on Github.

https://github.com/thank-you-github/thank-you-github

**Comment by lcrespom** [comment]
Yes, I know that letter :-). I thought there may be some workaround.

**Comment by Elecash** [comment]
I wish!! haha!

**Comment by ardiadrianadri** [comment]
:+1:

**Comment by ericzon** [comment]
:+1:

**Comment by Elecash** [comment]
Here's the code of this workshop!

https://github.com/angular2-virtual-list/angular2-virtual-list

Thank you to anyone that come to the workshop. If you want to be included as contributor of that repo just ping me and I'll be glad to add you :)
