### ISSUE TITLE
Migrate angularcamp.org to Angularjs :)

### ISSUE THREAD

**Issue by hhg2288** [AngularCamp/angularcamp.org#40]
I think it would be a good workshop to migrate the event website to angular:

- I would like to follow an approach Im working with recently with angular1.x + ES6, but the code structure like de Angular2 way: you can see an example [here](https://github.com/hhg2288/webpack-angular1x-es6). Or maybe just a simpler way, with the John Papa styleguide.

**Comment by ardiadrianadri** [comment]
:+1:
