### ISSUE TITLE
MVC - Model, The Great Forgotten

### ISSUE THREAD

**Issue by drpicox** [AngularCamp/angularcamp.org#43]
I’ll teach how to leverage in Model to simplify app creation and improve maintainability. Models are often forgotten in the web app development and they can solve lots of problems very quickly. I’ll put strong emphasis in the importance of the model and show some examples to learn the greatest of models. 
Between the examples I’ll add the synchronization of two scrollable areas.

**Comment by marcdeveloper** [comment]
:+1:

**Comment by drpicox** [comment]
There is the presentation:

- http://david-rodenas.com/posts/resources/Mvc%20-%20Model,%20the%20great%20forgotten.pdf

**Comment by jojuva** [comment]
Thanks for sharing!
