### ISSUE TITLE
Typescript, Angular 2, ionic 2, Meteor

### ISSUE THREAD

**Issue by johannes-weber** [AngularCamp/angularcamp.org#47]
Workshops on getting started with Typescript, best practices with angular 2, a tips and tricks for an ionic app that uses the ionic's push and analytics service.

Submitted by [Alejandro Serra](https://twitter.com/aserrabl)

**Comment by lcrespom** [comment]
An "e" is missing in "Typscript"

**Comment by ardiadrianadri** [comment]
:+1:

**Comment by arcnexus** [comment]
Yeahh, it sounds very interesting :+1:

**Comment by bloArribas** [comment]
cool
