### ISSUE TITLE
svg and other types of interaction

### ISSUE THREAD

**Issue by johannes-weber** [AngularCamp/angularcamp.org#48]
I'd like to see examples of angular mixed with other things than plain html, like svg, audio, video, 3d modelling, etc

Submitted by Salvador Subarroca

**Comment by DespertaWeb** [comment]
Sounds interesting, I'm feeling curious about svg  and it's potencial as well!

**Comment by subarroca** [comment]
I've been working a bit with svg but you never know where curiosity could lead you

**Comment by marcdeveloper** [comment]
Sounds interesting :+1:
