### ISSUE TITLE
How to apply the 'Angular Style Guide' (@johnpapa) on Angular2

### ISSUE THREAD

**Issue by AlbertoFuente** [AngularCamp/angularcamp.org#50]
It would be interesting to do a talk or workshop on how to apply the [Angular Style Guide](https://github.com/johnpapa/angular-styleguide) proposed by @johnpapa in Angular2, as a guide of good practices.

**Comment by ardiadrianadri** [comment]
:+1:

**Comment by johnpapa** [comment]
its coming :)

**Comment by lcrespom** [comment]
@johnpapa Are you coming to Barcelona to do the talk? :-)

**Comment by johnpapa** [comment]
no :) would be fun tho.

the starting point for the guide is in the works tho

**Comment by lcrespom** [comment]
Oooh... well, let's see if we got it right when we compare it with your guide

**Comment by sazimi** [comment]
@johnpapa We all are waiting for your  **style guide** :)

**Comment by AlbertoFuente** [comment]
@johnpapa Perhaps for the next AngularCamp we will see you in Barcelona? :stuck_out_tongue_winking_eye:
