### ISSUE TITLE
Angular2 Unit Testing

### ISSUE THREAD

**Issue by AlbertoFuente** [AngularCamp/angularcamp.org#53]
It would be interesting to do a workshop on best practices for unit testing in Angular2.

**Comment by johannes-weber** [comment]
Thx for you workshop proposal! 👍

**Comment by AlbertoFuente** [comment]
Here you have a very useful tutorial of @DanWahlin

http://www.syntaxsuccess.com/viewarticle/angular-2.0-unit-testing

**Comment by Elecash** [comment]
I've published today a new blog post about exactly that!

http://twofuckingdevelopers.com/2016/01/testing-angular-2-with-karma-and-jasmine/

**Comment by AlbertoFuente** [comment]
@Elecash great post!! :+1:

**Comment by Elecash** [comment]
Thanks! :smile:

**Comment by ardiadrianadri** [comment]
:+1:
