### ISSUE TITLE
Future apps with Angular2 and companions: Ionic2 + Firebase

### ISSUE THREAD

**Issue by johannes-weber** [AngularCamp/angularcamp.org#54]
Do you want to look into the future? How will we create web and mobile applications in 2016? Well, it's possible even without inventing time machine. Let's just take alpha/beta-versions of the most promising frameworks, add some magic and cook the app. The reference app for all the developers. Web or mobile - who cares, there will be only fine line between these in 2016. Sounds ambitious? 100%! But we love ventures and being on cutting edge of web technologies, so let's go for it!

Submitted by [https://twitter.com/webmaxru](Maxim Salnikov)

**Comment by marcdeveloper** [comment]
Great for at least one of my projects. :+1:
