### ISSUE TITLE
Angular2 workshop - up and running!

### ISSUE THREAD

**Issue by nirkaufman** [AngularCamp/angularcamp.org#56]
Come and get your hands dirty with Angular2!
During this workshop we will build up a fully working Angular 2 application on top of a modern front-end web development stack: npm, webpack and TypeScript.
We will touch most of the aspects that the Angular platform has to offer such as: Components, Providers, Pipes, Templates, Core directives and Http requests. 
By the end of this sessions, you will be able to start building your own applications with Angular2.
It's going to be fun!
*No prior experience with angular needed, but you must know how to write JS/HTML/CSS

**Comment by ardiadrianadri** [comment]
:+1:

**Comment by alvarocabanas** [comment]
:+1:

**Comment by marcdeveloper** [comment]
Yeah, sounds excellent :100:
