### ISSUE TITLE
Mastering Services in Angular 1.x

### ISSUE THREAD

**Issue by nirkaufman** [AngularCamp/angularcamp.org#63]
Services are a core concept of Angular, but also one of the confusing parts of the framework.
During this talk, we will dive deep into Angular Dependency Injection System and learn how we can leverage the power of services to build modular maintainable applications that scale.
All your questions will be answered!

During this session you will learn:
- How Angular injector works behind the scenes
- The difference between service, factory, provider, constant and value
- How to extend 3rd party services
- How to use cases and common patterns by examples
- Code conventions and best practices

**Comment by cblascos** [comment]
It's very interesting!!

**Comment by merqurio** [comment]
@nirkaufman Great talk! Can you please share the slides ¿? Thanks! :grin:

**Comment by merqurio** [comment]
Found them ! Link to the [repo](/nirkaufman/angularjs-services)
