### ISSUE TITLE
Reactive programming in Angular 2

### ISSUE THREAD

**Issue by wizardofjoz** [AngularCamp/angularcamp.org#67]
Just got the hang of using promises? Get ready for streams!  
Angular 2 adopts Reactive Extensions with RxJs in which everything can be thought of as a stream of events. They're like promises on steroids but yet another concept to learn when starting with Angular 2.

**Comment by johannes-weber** [comment]
:+1:

**Comment by lcrespom** [comment]
:+1:

**Comment by marcdeveloper** [comment]
:+1:
