### ISSUE TITLE
SVG in AngularJS

### ISSUE THREAD

**Issue by shmool** [AngularCamp/angularcamp.org#70]
Referencing @johannes-weber interest, although I do not have a ready talk about SVG in Angular, I am willing to share my experience and explore this area with you. I have been working with SVG in my current Angular 1.4 project. I have tried various methods, starting off with D3 and moving to more Angularic ways to bind the data to the drawings. I have encountered a few interesting cases when combining Angular directives with SVG attributes, and when directivising SVG components. I will be happy to hear your experience and suggestions as well!

**Comment by paveliko** [comment]
@shmool I have an experience with SVG in Angular. I built a few diagrams for startups and now develop ETL package designer at Xplenty, based on SVG and Angular. I'll be glad to share with you my knowledge.

**Comment by karolinkaIn** [comment]
Yiehah, can you share with us your knowledge?? Did you have slides?

**Comment by DespertaWeb** [comment]
Hey I'm very very very very very interested on your slides/whatever you wanted to show at angular Camp! could you please upload and share them to Angular Camp meetup please? We are a few still interested on :D

**Comment by shmool** [comment]
Hey :) I'll be happy to share my knowledge. I've been working with SVG in a client's project which is not public, so I can't show it as is... I'll prepare something in the next few days and post a link here. 
In the meantime there is a plnkr I made for one of my interesting use cases: http://plnkr.co/edit/XAxBPwAhGwwzzNYrmCFm?p=preview - I will add explanations later on.
@paveliko I'd love to see your work! I'm sure everybody else would also. Is there anything you can share?

**Comment by shmool** [comment]
Hey people! My boss gave a lecture in our meetup exactly about this topic, based on the project we work on! It sums up exactly what you need to know about Angular+SVG+a little d3
Here are the slides: http://www.slideshare.net/500Tech/d3-svg-angular-58561584
And the code: https://github.com/adamkleingit/d3-svg-angular
The video will be published soon on our YouTube channel, and even though it's in Hebrew I bet you can understand the key concepts :) I'll tell you when it's ready.

**Comment by davidpich** [comment]
Thanks for sharing @shmool !

**Comment by shmool** [comment]
Hey there! Another short blog post about SVG in Angular2: http://blog.500tech.com/svg-in-angular-2/
