### ISSUE TITLE
Workshop Angular 1.5 + ES6 en Castellano

### ISSUE THREAD

**Issue by carlosazaustre** [AngularCamp/angularcamp.org#72]
Workshop de 45m - 1h de duración (aprox.) en Castellano donde se vería el desarrollo de una App basada en componentes utilizando Angular 1.5 y ECMAScript 6 siguiendo la guía de estilo de Todd Motto.
Bundle con Browserify y utilizando NPM Scripts.
- [Repository Code](https://github.com/carlosazaustre/angularcamp-workshop)
- [Tutorial](https://carlosazaustre.es/blog/desarrollo-por-componentes-con-angular-1-5-con-es6-es2015/)

Spoiler Alert ;)
![Angular App](https://carlosazaustre.es/blog/content/images/2016/07/ezgif-1440086715.gif)

**Comment by DespertaWeb** [comment]
Interesante !  Yo no podré ir, pues estoy en Alaska. Me gustaría saber si colgarás el taller en youtube o aquí. 

Gràcies!

**Comment by carlosazaustre** [comment]
@DespertaWeb Hola! Acabo de publicar un tutorial en mi blog con el workshop. Espero que te guste!
[Link](https://carlosazaustre.es/blog/desarrollo-por-componentes-con-angular-1-5-con-es6-es2015/)
