### ISSUE TITLE
Brainwaves in Angular 2

### ISSUE THREAD

**Issue by alexcastillo** [AngularCamp/angularcamp.org#78]
![my-bci](https://cloud.githubusercontent.com/assets/1181666/15448454/38946208-1f30-11e6-9a96-6705d9196c0f.png)

Come see a demonstration on how to interact with an open-source brain-computer interface via JavaScript. Alex has been working with the OpenBCI team in order to visualize and interpret brainwaves in the browser with Angular 2. Find out how your thoughts are captured and how to get involved in the NeuroTech community.

**Comment by ardiadrianadri** [comment]
Really intersting. I never thought to use Angular 2 in that way  :+1:

**Comment by silentHoo** [comment]
Hm, interesting ;) Would like to hear a talk about that!
