### ISSUE TITLE
The last of "them": new component router for AngularJS & Angular2 apps

### ISSUE THREAD

**Issue by semagarcia** [AngularCamp/angularcamp.org#79]
In this talk I'd like to review the "conceptual roadmap" followed by Angular from earlier versions (AngularJS 1.x) to the newest one (Angular2) with examples. I also share with you the differents approaches of each type of router.

Other topic covered by this talk if it is choosen is the possibility way to enable the Angular2 router in Angular1.x apps in order to smooth the possible transition or migration to the new version.

**Comment by ardiadrianadri** [comment]
:+1:

**Comment by Fermartyni** [comment]
👍

**Comment by shprink** [comment]
Is it the new new (RC) or the new deprecated (Alpha, Beta)?

**Comment by semagarcia** [comment]
Yes, that is the idea... to cover even the last router (new new RC as you said), from AngularJS 1.x to Angular2
