### ISSUE TITLE
Creating a mobile app using Angular 2 with Ionic 2

### ISSUE THREAD

**Issue by mrcabellom** [AngularCamp/angularcamp.org#80]
The main idea of this talk is to show an applications developed using Ionic 2. In a first part, we will introduce Ionic 2 with Angular 2 using typescript. We also talk about technologies our project will cover tooling like browserify, tsify, cordova plugins such as touchid, camera. etc. 

We will learn about several angular 2 modules:
- http module
-  rxjs
- ngZone
- pipes

Also we will cover application unit testing with jasmine using sync and async specs. 

In the second part, we show a project developed that obtain the wait time average of the attractions of Disney Land Paris, showing an attraction color depending on his wait time. Finally, we will show our app running on different mobile devices

Aprox. Duration: 1 hour

**Comment by rliberoff** [comment]
Cool!

**Comment by xmontero** [comment]
I want to be in this one.

I am willing to explore how to make an app "from scratch" and learning even how to install the toolset. I will be using a windows laptop and I have VirtualBox if I need any linux for the command-lines. I don't have Mac, I hope I don't "need" a Mac to follow the session. I am more a PHP guy, DDD and TDD oriented, rather purist at modelling, but I'm kind of lost on how ionic can bring an approximation to a WYSIWYG to mobile... I know several languanges, from the 90's, like VB, C, C++, PHP, even assembler of the Z80 and Motorola 68k, but... frankly speaking, I've not yet coded in angular by myself. So I hope I don't need to "pre-know" angular to run into this workshop.

My ultimate goal is to learn how to setup a some kind of R.A.D. environment for mobile.

So my desire: if I come with an idea in the morning, and I have a few mockups/wireframes in the lunch-time, I want to be able to have a running app at dinner-time.

Similar to the same way I did 20 years ago, back in the 90's, with Visual Basic: Just imagine, draw the interface, fill-in the code triggered in the events, and boom, done!

Will this be "the" workshop? All the payment of ticket devoted to THIS one!! From the idea to a runing app in the mobile in less than 1 day. This is what I would expect to learn.

**Comment by xmontero** [comment]
As told in here https://github.com/AngularCamp/angularcamp.org/issues/99 , I hope the time for this one does not overlap with the other, as I want to be in BOTH.

**Comment by xmontero** [comment]
From a planification of timetables and calendars point of view... do we know if this talk is gonna be done, and what day and time?

**Comment by CarlosLanderas** [comment]
Here are the slides of our Ionic2 with Angular2 application talk at Angular Camp. I hope you enjoyed the talk.

Link:
https://drive.google.com/file/d/0B9Nw9gz-IFgBdnYtMkl4N05mOUk/view?usp=sharing
