### ISSUE TITLE
Angular2 + New Firebase in Action

### ISSUE THREAD

**Issue by ruchavarri** [AngularCamp/angularcamp.org#97]
**Type:** Practical Talk with a lot of demos
**Expected duration:** 1h

**Description** 
We will talk about how to mix Angular2 and the new FireBase, one of the latest GoogleI/O surprises, a Mobile Backend as a Service, Realtime and Hosting service. We will have also a little introduction to reactive programming, how to build interactive applications and how to take advantage of this new approach in our apps.  
In the talk we will use the following libraries among others:
- [Angular2 + RxJS](https://angular.io/docs/ts/latest/guide/server-communication.html#!#rxjs)
- [AngularFire2](https://github.com/angular/angularfire2)
- [New FireBase](https://firebase.google.com/)
- [Angular Material](https://material.angular.io/)

We will end up developing an interactive application which will show the potential of this awesome synergy Angular2 + New Firebase, with a collaborative example ;)

A little spoilers about the proposal. An example challenging Firebase with Interactive multiplayer board:
![angular2-fireboard](http://i.giphy.com/xT8qB0NwdZjEiPbxL2.gif)

**Prerequisites:**
None.

**Comment by Jeffarese** [comment]
Just a question, since AngularFire isn't compatible with Firebase SDK 3.0, when you talk about new Firebase you mean the old 2.0 SDK, right?

**Comment by ruchavarri** [comment]
Hi Jeffarese,
In the workshop we will publish an app using the new FireBase Console integrated in the Google Portal https://firebase.google.com/docs/cli/
As you mention, AngularFire2 is built over Firebase sdk 2.4. Good news that David East and Jeff Cross are working in the migration to sdk 3.0 ;) 
We know, angularFire2 have some limitations at this point, we will work around them and see other pretty cool new features too. We will share a few demos showing how it works.

I hope to see you in the Camp.

**Comment by ruchavarri** [comment]
Dave East and Jeff Cross have just released a fresh update which upgrade their AngularFire2 library to use **FireBase SDK 3.0**. 
To see feel the improvement, we have updated our example to see it in action.

**Comment by DvdChavarri** [comment]
https://drive.google.com/file/d/0BzYqOEpHkTc9OW1wUjRuN05UcnM
