### ISSUE TITLE
Ionic2 - Mi primera aplicación (Spanish)

### ISSUE THREAD

**Issue by carlosrubio** [AngularCamp/angularcamp.org#99]
**Type**: Workshop 

**Expected duration**: 1h

**Description** 
_This session would be carried out in Spanish_ 

La idea es hacer tu primera aplicación con Ionic2. Ver la estructura básica, usar navegación, un menu, y algunos componentes nativos. 

Sera una sesión introductoria para gente que nunca ha trabajado con Ionic 2.

**Prerequisites:**
- Node 5.x, 6.x (probablemente otros funcionaran tambien)
- Ionic CLI (instalable desde npm)
- Cordova (instalble desde npm)
- Editor de preferencia (Atom, WebStorm, VS Code,...) 

Instrucciones  de instalación Ionic2--> [Aqui](http://ionicframework.com/docs/v2/getting-started/installation/)

**Comment by xmontero** [comment]
I hope this session is NOT at the same time than this one: https://github.com/AngularCamp/angularcamp.org/issues/80 as I want to be on BOTH.

Same comment done there applies here (crossposted for reading convenience)!!

[Begin of Crosspost]
I want to be in this one.

I am willing to explore how to make an app "from scratch" and learning even how to install the toolset. I will be using a windows laptop and I have VirtualBox if I need any linux for the command-lines. I don't have Mac, I hope I don't "need" a Mac to follow the session. I am more a PHP guy, DDD and TDD oriented, rather purist at modelling, but I'm kind of lost on how ionic can bring an approximation to a WYSIWYG to mobile... I know several languanges, from the 90's, like VB, C, C++, PHP, even assembler of the Z80 and Motorola 68k, but... frankly speaking, I've not yet coded in angular by myself. So I hope I don't need to "pre-know" angular to run into this workshop.

My ultimate goal is to learn how to setup a some kind of R.A.D. environment for mobile.

So my desire: if I come with an idea in the morning, and I have a few mockups/wireframes in the lunch-time, I want to be able to have a running app at dinner-time.

Similar to the same way I did 20 years ago, back in the 90's, with Visual Basic: Just imagine, draw the interface, fill-in the code triggered in the events, and boom, done!

Will this be "the" workshop? All the payment of ticket devoted to THIS one!! From the idea to a runing app in the mobile in less than 1 day. This is what I would expect to learn.
[End of Crosspost]

**Comment by xmontero** [comment]
De cara a la planificación de horarios y calendarios... ¿se sabe si esta charla se va a hacer yes/no y en qué dia y hora?
